# Generated by Django 4.1.7 on 2023-03-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schema", "0002_alter_column_first_name_alter_column_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schema",
            name="column_type",
        ),
        migrations.AddField(
            model_name="schema",
            name="columns",
            field=models.ManyToManyField(related_name="schemas", to="schema.column"),
        ),
    ]
