# Generated by Django 4.1.7 on 2023-03-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schema", "0008_dataset_is_generated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="column",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="column",
            name="last_name",
        ),
    ]
